### ISSUE TITLE
Clickhouse `join` syntax can't be enclosed in brackets.

### ISSUE THREAD

**Issue by goldmedal** [tobymao/sqlglot#3735] opened 2024-07-03 16:08 UTC
**Fully Reproducible Code Snippet**
```python
import sqlglot
input_sql = 'select * from (orders join customer on o_custkey = c_custkey)'
expected = 'SELECT * FROM "orders" JOIN "customer" ON "o_custkey" = "c_custkey"'

if __name__ == "__main__":
    actual = sqlglot.transpile(input_sql, read="trino", write="clickhouse", identify=True, pretty=False)[0]
    # it will print `SELECT * FROM ("orders" JOIN "customer" ON "o_custkey" = "c_custkey")`
    print(actual)
    assert actual == expected
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
```
[FROM [db.]table | (subquery) | table_function] [FINAL]
```
Clickhouse only allows `subquery` in the brackets behind `from`.  
The documentation for the select syntax: [Clickhouse Select Syntax](https://clickhouse.com/docs/en/sql-reference/statements/select#syntax)

**Comment by VaggelisD** [comment] 2024-07-03 17:04
Hey @goldmedal, thanks for reporting this. 

> Clickhouse only allows subquery in the brackets behind from.

Could you please expand on that? 

According to the [docs](https://clickhouse.com/docs/en/sql-reference/statements/select/from), a `subquery` must be a `SELECT` query, so I think that the issue is that `FROM (orders join ... )` doesn't conform to the spec. For example, this works fine in CH:

```SQL
WITH t1 AS (SELECT 1 AS id UNION ALL SELECT 2 AS id), t2 AS (SELECT 1 AS id) SELECT * FROM (SELECT id FROM t1 JOIN t2 ON t1.id=t2.id);
```

**Comment by goldmedal** [comment] 2024-07-03 17:15
Thanks @VaggelisD 

> According to the [docs](https://clickhouse.com/docs/en/sql-reference/statements/select/from), a `subquery` must be a `SELECT` query, so I think that the issue is that `FROM (orders join ... )` doesn't conform to the spec. For example, this works fine in CH:

Yes, that's exactly what I mean. `FROM (orders join ... )` doesn't conform to the spec. I just wanted to highlight what can be enclosed in brackets in CH. 
Sorry for confusing you.

**Comment by VaggelisD** [comment] 2024-07-03 17:29
I see what you mean, thanks for clarifying. So if I understand correctly, Trino doesn't have an issue with these parentheses (while also **not** considering this a subquery) but Clickhouse attempts to match `FROM (subquery)` upon coming across this pattern, which causes the error.

I'll go ahead and close this as not planned for the time being; I think I have a possible fix but it could prove both ambiguous and cause side-effects down the line. I'll let the other contributors chime in with their opinions as well.

**Closed by VaggelisD** 2024-07-03 17:29 UTC

**Comment by goldmedal** [comment] 2024-07-03 17:39
Sure. Thanks again @VaggelisD

**Comment by goldmedal** [comment] 2024-07-04 03:26
Just provider another related case. If you plan to fix the issue, it might also need to be fixed.
```python
import sqlglot
input_sql = 'select * from (orders join customer on o_custkey = c_custkey) as j1'
expected = 'SELECT * FROM "orders" JOIN "customer" ON "o_custkey" = "c_custkey"'

if __name__ == "__main__":
    actual = sqlglot.transpile(input_sql, read="trino",write="clickhouse", identify=True, pretty=False)[0]
    # it will print `SELECT * FROM ("orders" JOIN "customer" ON "o_custkey" = "c_custkey") `
    print(actual)
    assert actual == expected
```

Trino and DuckDB allow the use of aliases for join relations. I think these aliases should be removed when converting to CH SQL.

**Comment by tobymao** [comment] 2024-07-04 03:29
it's not so simple because the semantics of (x join y) are not the same as from x join y

**Comment by goldmedal** [comment] 2024-07-04 03:35
> it's not so simple because the semantics of (x join y) are not the same as from x join y

Indeed. How about throwing warnings or errors in this case when converting to CH SQL?

**Comment by tobymao** [comment] 2024-07-04 03:43
i don't think there's a need because if this is invalid in clickhouse, it should raise an error when you execute it
