### ISSUE TITLE
bug(snowflake): error in second-pass of `add_within_group_for_percentiles`

### ISSUE THREAD

**Issue by gforsyth** [tobymao/sqlglot#3257] opened 2024-04-01 20:55 UTC
Apologies for not having a reproducer for this, but in Ibis, we have a query with two calls to `percentile_cont` and the expression we generate looks like this:

```python
Select(
  expressions=[
    Alias(
      this=PercentileCont(
        this=Column(
          this=Identifier(this=ROW_COUNT, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        expression=Literal(this=0.25, is_string=False)),
      alias=Identifier(this=quantile_0_25_row_count, quoted=True)),
    Alias(
      this=PercentileCont(
        this=Column(
          this=Identifier(this=ROW_COUNT, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        expression=Literal(this=0.75, is_string=False)),
      alias=Identifier(this=quantile_0_75_row_count, quoted=True))],
  from=From(
    this=Table(
      this=Identifier(this=TABLES, quoted=True),
      db=Identifier(this=INFORMATION_SCHEMA, quoted=True),
      alias=Identifier(this=t0, quoted=True))))
```

if we generate Snowflake SQL from this (a user reported this issue with our Snowflake backend), it works as expected and hits the rewrite rule `add_within_group_for_percentiles`.  it does what it says on the box, and adds the "WITHIN GROUP" and orders by the column.

```python
>>> print(sg_expr.sql(dialect="snowflake", pretty=True))
SELECT
  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_25_row_count",
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_75_row_count"
FROM "INFORMATION_SCHEMA"."TABLES" AS "t0"
```

However if we set `copy=False` on the call to `sql` that same rule errors -- I can only reproduce this if we have two separate calls to quantile, so I believe in the first pass, the mutation is removing some portion of the expression that the rewrite rule is expecting to still exist.

```python
>>> print(sg_expr.sql(dialect="snowflake", pretty=True, copy=False))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[74], line 1
----> 1 print(sg_expr.sql(dialect="snowflake", pretty=True, copy=False))

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/expressions.py:561, in Expression.sql(self, dialect, **opts)
    549 """
    550 Returns SQL string representation of this tree.
    551 
   (...)
    557     The SQL string.
    558 """
    559 from sqlglot.dialects import Dialect
--> 561 return Dialect.get_or_raise(dialect).generate(self, **opts)

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/dialects/dialect.py:498, in Dialect.generate(self, expression, co
py, **opts)
    497 def generate(self, expression: exp.Expression, copy: bool = True, **opts) -> str:
--> 498     return self.generator(**opts).generate(expression, copy=copy)

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:583, in Generator.generate(self, expression, copy)
    580 expression = self.preprocess(expression)
    582 self.unsupported_messages = []
--> 583 sql = self.sql(expression).strip()
    585 if self.pretty:
    586     sql = sql.replace(self.SENTINEL_LINE_BREAK, "\n")

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:734, in Generator.sql(self, expression, key, comment
)
    731 transform = self.TRANSFORMS.get(expression.__class__)
    733 if callable(transform):
--> 734     sql = transform(self, expression)
    735 elif isinstance(expression, exp.Expression):
    736     exp_handler_name = f"{expression.key}_sql"

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/transforms.py:601, in preprocess.<locals>._to_sql(self, expressio
n)
    599 _sql_handler = getattr(self, expression.key + "_sql", None)
    600 if _sql_handler:
--> 601     return _sql_handler(expression)
    603 transforms_handler = self.TRANSFORMS.get(type(expression))
    604 if transforms_handler:

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:2199, in Generator.select_sql(self, expression)
   2196 else:
   2197     top = ""
-> 2199 expressions = self.expressions(expression)
   2201 if kind:
   2202     if kind in self.SELECT_KINDS:

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:3229, in Generator.expressions(self, expression, key
, sqls, flat, indent, skip_first, sep, prefix)
   3227 result_sqls = []
   3228 for i, e in enumerate(expressions):
-> 3229     sql = self.sql(e, comment=False)
   3230     if not sql:
   3231         continue

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:739, in Generator.sql(self, expression, key, comment
)
    736 exp_handler_name = f"{expression.key}_sql"
    738 if hasattr(self, exp_handler_name):
--> 739     sql = getattr(self, exp_handler_name)(expression)
    740 elif isinstance(expression, exp.Func):
    741     sql = self.function_fallback_sql(expression)

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:2725, in Generator.alias_sql(self, expression)
   2723 alias = self.sql(expression, "alias")
   2724 alias = f" AS {alias}" if alias else ""
-> 2725 return f"{self.sql(expression, 'this')}{alias}"

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:728, in Generator.sql(self, expression, key, commen$
)
    726     value = expression.args.get(key)
    727     if value:
--> 728         return self.sql(value)
    729     return ""
    731 transform = self.TRANSFORMS.get(expression.__class__)

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/generator.py:734, in Generator.sql(self, expression, key, commen$
)
    731 transform = self.TRANSFORMS.get(expression.__class__)
    733 if callable(transform):
--> 734     sql = transform(self, expression)
    735 elif isinstance(expression, exp.Expression):
    736     exp_handler_name = f"{expression.key}_sql"

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/transforms.py:595, in preprocess.<locals>._to_sql(self, expressi$
n)
    592 def _to_sql(self, expression: exp.Expression) -> str:
    593     expression_type = type(expression)
--> 595     expression = transforms[0](expression)
    596     for transform in transforms[1:]:
    597         expression = transform(expression)

File /nix/store/h8il4c7m03m95gc9f880ncqhp5fr2njd-python3-3.11.8-env/lib/python3.11/site-packages/sqlglot/transforms.py:329, in add_within_group_for_percentiles(expressio$
)
    323 """Transforms percentiles by adding a WITHIN GROUP clause to them."""
    324 if (
    325     isinstance(expression, PERCENTILES)
    326     and not isinstance(expression.parent, exp.WithinGroup)
    327     and expression.expression
    328 ):
--> 329     column = expression.this.pop()
    330     expression.set("this", expression.expression.pop())
    331     order = exp.Order(expressions=[exp.Ordered(this=column)])

AttributeError: 'NoneType' object has no attribute 'pop'
```

I can work around this by either setting `copy=True` or constructing the initial sqlglot expression with the `within group` already present to skip over the rewrite rule.  

If I come up with a reasonable reproducer I'll be sure to add it here.

**Comment by gforsyth** [comment] 2024-04-01 20:56
xref ibis-project/ibis#8768

**Comment by georgesittas** [comment] 2024-04-01 22:18
Hey @gforsyth, this may be related to how you're constructing the AST. I constructed the AST you shared manually and couldn't repro the issue, so my guess is the two `PercentileCont`s in your AST are the same reference and that causes problems.

```python
>>> from sqlglot.expressions import (
...     Alias,
...     Column,
...     From,
...     Identifier,
...     Literal,
...     PercentileCont,
...     Select,
...     Table,
... )
>>>
>>> ast = Select(
...     **{
...         "expressions": [
...             Alias(
...                 this=PercentileCont(
...                     this=Column(
...                         this=Identifier(this="ROW_COUNT", quoted=True),
...                         table=Identifier(this="t0", quoted=True)
...                     ),
...                     expression=Literal(this="0.25", is_string=False)
...                 ),
...                 alias=Identifier(this="quantile_0_25_row_count", quoted=True)
...             ),
...             Alias(
...                 this=PercentileCont(
...                     this=Column(
...                         this=Identifier(this="ROW_COUNT", quoted=True),
...                         table=Identifier(this="t0", quoted=True)
...                     ),
...                     expression=Literal(this="0.75", is_string=False)
...                 ),
...                 alias=Identifier(this="quantile_0_75_row_count", quoted=True)
...             )
...         ],
...         "from": From(
...             this=Table(
...                 this=Identifier(this="TABLES", quoted=True),
...                 db=Identifier(this="INFORMATION_SCHEMA", quoted=True),
...                 alias=Identifier(this="t0", quoted=True)
...             )
...         )
...     }
... )
>>> ast
Select(
  expressions=[
    Alias(
      this=PercentileCont(
        this=Column(
          this=Identifier(this=ROW_COUNT, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        expression=Literal(this=0.25, is_string=False)),
      alias=Identifier(this=quantile_0_25_row_count, quoted=True)),
    Alias(
      this=PercentileCont(
        this=Column(
          this=Identifier(this=ROW_COUNT, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        expression=Literal(this=0.75, is_string=False)),
      alias=Identifier(this=quantile_0_75_row_count, quoted=True))],
  from=From(
    this=Table(
      this=Identifier(this=TABLES, quoted=True),
      db=Identifier(this=INFORMATION_SCHEMA, quoted=True),
      alias=Identifier(this=t0, quoted=True))))
>>>
>>> print(ast.sql("snowflake", pretty=True))
SELECT
  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_25_row_count",
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_75_row_count"
FROM "INFORMATION_SCHEMA"."TABLES" AS "t0"
>>> print(ast.sql("snowflake", pretty=True, copy=False))
SELECT
  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_25_row_count",
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY
    "t0"."ROW_COUNT") AS "quantile_0_75_row_count"
FROM "INFORMATION_SCHEMA"."TABLES" AS "t0"
```

I'll go ahead and close this for now as it looks like there's no issue, but happy to discuss more / reopen if you can share a reproducible example.

**Closed by georgesittas** 2024-04-01 22:18 UTC

**Comment by gforsyth** [comment] 2024-04-02 13:17
Hey @georgesittas -- thanks for the pointers!  I'll poke at our AST construction a bit more and see if I can track down any duplicate references.
