### ISSUE TITLE
Oracle: DATE and other literal semantics

### ISSUE THREAD

**Issue by deliciouslytyped** [tobymao/sqlglot#1409] opened 2023-04-10 20:17 UTC
```
>>> sqlglot.parse("select DATE '1990-01-01' FROM dual", "oracle")[0].sql("oracle")
"SELECT CAST('1990-01-01' AS DATE) FROM dual"
```

These are not the same, but I'm not sure what I should do about it.

The semantics of the CAST depend on (or at least are stated to be the same as / similar to) TO_DATE, which depends on NLS variables. (explained in this section https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/sql-language-reference.pdf#page=349&zoom=auto,-90,593 )
For example though the ANSI DATE literal is valid, the following cast is not valid if the default date format is something else:
```
select CAST('1990-01-01' AS DATE) from dual;

ORA-01861: "literal does not match format string"
*Cause:    Literals in the input must be the same length as literals in
           the format string (with the exception of leading whitespace).  If the
           "FX" modifier has been toggled on, the literal must match exactly,
           with no extra whitespace.
*Action:   Correct the format string to match the literal.
```
whereas the date literal is apparently from ANSI SQL, there are also TIMESTAMP literals two pages later, where I have similar concerns (and the other two similar datetime literal types).
 https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/sql-language-reference.pdf#page=95&zoom=auto,-90,122 

Some slightly additional info at:
stevenfeuersteinonplsql.blogspot.com/2017/08/using-date-literal-in-oracle-database.html

```
>>> sqlglot.parse("select TIMESTAMP '2000-03-28 08:00:00' FROM dual", "oracle")[0].sql("oracle")
"SELECT CAST('2000-03-28 08:00:00' AS TIMESTAMP) FROM dual"
```

**Comment by tobymao** [comment] 2023-04-10 20:44
it doesn't seem to be problematic nor does there seem to be a solution.

so i'm going to close this as not planned. happy to discuss more and come up with an appropriate solution

**Closed by tobymao** 2023-04-10 20:44 UTC

**Comment by deliciouslytyped** [comment] 2023-04-10 21:25
What do you mean it doesn't seem problematic?

Also I think I failed to actually state my point: The TIMESTAMP and DATE literals don't depend on NLS so they should not be translated to something that depends on NLS.

**Comment by tobymao** [comment] 2023-04-10 21:33
oracle isn't really a big concern of mine since sqlglot's primary use case is for analytical workloads.

DATE '1990-01-01' is the same as CAST('1990-01-01' AS DATE) right? 

i'm sure there are edge cases where this doesn't work but the seem minimal

**Comment by deliciouslytyped** [comment] 2023-04-10 22:33
Thinking about it more, no - they aren't the same.

The problem is, I think, this will immediately come up in any environment where someone uses any date literal and their date format isn't set to the same as the ANSI format / the format specified for the given literal type. This is probably true of any English language server given the `MM/DD/YYYY` format, not just international ones.

The question I think is more how often a date literal is used, than whether `DATE '...'` and `CAST('...' AS DATE)` are the same.

Anyway if you don't want to work on this, it's fine, I just figured I'd mention it.
For my specific use case I got around the problem with some ugly hacking.

**Comment by tobymao** [comment] 2023-04-10 22:40
that's what i don't plan on changing, if it's more widespread than oracle or if i ever get the need to support this feature in oracle, then the solution would be to treat date '...' different from cast('...' as date)

so if you can find other databases where date '...' is different from cast(...) i can add it

**Comment by mpf82** [comment] 2023-04-10 23:37
Just my 2 cents: maybe the parser in the Oracle dialect could convert ``DATE '1990-01-01'`` to ``TO_DATE('1990-01-01', 'yyyy-mm-dd')``.

That should always be correct, right? Since the date literal is always expected to be in the form ``yyyy-mm-dd`` and ``TO_DATE`` allows you to specify the format mask (unlike CAST).

**Comment by tobymao** [comment] 2023-04-10 23:43
this is an easy change, just need a slight restructure to make _parse_type more subclassable

```
    def _parse_type(self) -> t.Optional[exp.Expression]:
        if self._match(TokenType.INTERVAL):
            return self.expression(
                exp.Interval,
                this=self._parse_term(),
                unit=self._parse_field(tokens=self.INTERVAL_VARS),
            )

        index = self._index
        type_token = self._parse_types(check_func=True)
        this = self._parse_column()

        if type_token:
            if isinstance(this, exp.Literal):
                return self.expression(exp.Cast, this=this, to=type_token)
```

**Comment by tobymao** [comment] 2023-04-10 23:44
perhaps we can make the Cast a lambda and then override it in oracle to do that

**Comment by mpf82** [comment] 2023-04-10 23:57
I think, changing ``_parse_type`` is preferable over changing the result of ``cast_sql``, because there might be edge cases where there's originally a ``CAST(x AS DATE)`` that should stay as-is and not be converted to ``TO_DATE``, while chaging the DATE literal to TO_DATE should always be correct.

Unless I'm overthinking this ...

**Comment by tobymao** [comment] 2023-04-11 02:45
if you can confirm that the solution is to have oracle do

date '...' -> TO_DATE(..., fixed_format) and 
timestamp '...' -> TO_DATE(..., fixed_format)

then i will accept a PR that adds this to _parse_type as a dictionary of lambdas or do this myself because it seems pretty easy

**Comment by mpf82** [comment] 2023-04-12 08:35
I've done some research, and the DATE literals seem to be actually ANSI SQL-92 standard:

https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt (see section ``5.3 <literal>``)

as I understand, the general syntax is:

```sql
DATE '1999-09-19'
TIME '12:34:56'
TIMESTAMP '1999-09-19 12:34:56' 
```

timestamp being tricky, as it also supports fractional seconds precision and time zones:

```sql
TIMESTAMP '1997-01-31 09:26:56.66 +02:00'
```

and then there's also an ODBC DATE literals standard:

```sql 
{d '1999-09-19'}
{t '12:34:56'}
{ts '1999-09-19 12:34:56'}
```

references:

https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/date-time-and-timestamp-literals?view=sql-server-ver16
https://mariadb.com/kb/en/date-and-time-literals/
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html
https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements003.htm#sthref364
https://www.oreilly.com/library/view/oracle-plsql-programming/9780596805401/ch10s05.html
https://count.co/sql-resources/bigquery-standard-sql/dates-and-times

So, maybe the best thing to do is to not convert DATE literals into CAST / TO_DATE at all, since they are ANSI standard and should be supported by all dialects? 

On the other hand, it might make sense to convert ODBC DATE literals to ANSI DATE literals, to make them more standard.

In the end it's of course up to you how sqlglot handles ANSI DATE literals.

**Comment by tobymao** [comment] 2023-04-12 14:47
can you confirm whether or not other dialects have differences between date literal and cast date?

**Comment by tobymao** [comment] 2023-04-12 15:52
from my perspective, i only wanted one representation of things. int '1' == cast(1 as int), and so i made the same assumption for date and timestamp

it seems like the problem is date '2022-01' can be configured with some flags in certain dialects, but if you use these configurations, then your sql is not transpilable because your other system may not have the same flag

**Comment by mpf82** [comment] 2023-04-12 17:35
I've been playing around with the following statement on http://sqlfiddle.com

```sql
SELECT
   DATE '2015-01-01',
   CAST('2015-01-01' AS DATE),
   CAST('01-OCT-2015' AS DATE)
```

* mysql: result of ``CAST('01-OCT-2015' AS DATE)`` is ``NULL``
* sqlite: does not recognize DATE literal and complains about invalid column; result of ``CAST('01-OCT-2015' AS DATE)`` is ``1``
* postgres: result of all 3 is the same date value
* oracle: complains that ``CAST('2015-01-01' AS DATE)`` is not correctly formatted
* sql server: always a connection error

I also ran oracle specific tests and all except the commented line worked:

```sql
SELECT
   TIMESTAMP '2015-01-01 02:12:45',
   TIMESTAMP '2015-01-01 02:12:45.123',
   TIMESTAMP '1997-01-31 09:26:56.66 +02:00',
   TO_TIMESTAMP('2015-01-01 02:12:45', 'YYYY-MM-DD HH24:MI:SS'),
   TO_TIMESTAMP('2015-01-01 02:12:45.123', 'YYYY-MM-DD HH24:MI:SS.FF'),
   TO_TIMESTAMP('2015-01-01 02:12:45', 'YYYY-MM-DD HH24:MI:SS.FF'),
   TO_TIMESTAMP('2015-01-01', 'YYYY-MM-DD HH24:MI:SS.FF'),
   --TO_TIMESTAMP('1997-01-31 09:26:56.66 +02:00', 'YYYY-MM-DD HH24:MI:SS.FF TZH:TZM'),
   1
   from dual;
```

So if we want to go the CAST route, I'd say it's safe to use ``TO_DATE(X, 'YYYY-MM-DD')`` to replace DATE literals and `` TO_TIMESTAMP(X, 'YYYY-MM-DD HH24:MI:SS.FF')`` for TIMESTAMP literals.

Oracle does not support a TIME literal, neither a CAST(X AS TIME) and there's no ``TO_TIME`` function. the preferred way would be to convert a TIME literal to ``TO_DATE(X, 'HH24:MI:SS')``.

Little rant on the side: why do we even have an ANSI standard, if all the dialects do their own thing and don't even fully implement the standard. grumble grumble.

**Comment by tobymao** [comment] 2023-04-12 17:53
> Little rant on the side: why do we even have an ANSI standard, if all the dialects do their own thing and don't even fully implement the standard. grumble grumble.

haha. that's why SQLGlot exists :) standards don't mean anything.

you didn't test one case though which is what is the value of

DATE '01-OCT-2015' ?

**Comment by mpf82** [comment] 2023-04-12 20:20
``DATE '01-OCT-2015' `` is invalid in all dialects that support date literals, at least in those I could test.

``TO_DATE('01-OCT-2015')`` works in oracle with the English default settings but as already discussed depends on the NLS_DATE_FORMAT setting.

**Comment by tobymao** [comment] 2023-04-12 20:26
so it seems like the only "issue" is oracle

CAST('2015-01-01' AS DATE) causing an error in oracle whereas DATE '2015-01-01' works

**Comment by mpf82** [comment] 2023-04-13 00:17
Exactly.

In Oracle ``DATE '2015-01-01'`` can be translated to ``TO_DATE('2015-01-01', 'YYYY-MM-DD')``.

Same with ``TIMESTAMP '2015-01-01 02:12:45'``, which can be translated to ``TO_TIMESTAMP('2015-01-01 02:12:45', 'YYYY-MM-DD HH24:MI:SS.FF')``.

And ``TIME '02:12:45'`` can be tranlated to ``TO_TIMESTAMP('02:12:45', 'HH24:MI:SS.FF')``.

That should pretty much cover all cases, except when TIMESTAMP contains a timezone information.

**Comment by tobymao** [comment] 2023-04-13 05:22
i've added the date literals for oracle, this commit adds the structure needed for the other variants which i'll leave up to you two if you're interested

https://github.com/tobymao/sqlglot/commit/dbdcee8bcb3d2859f0fdccfbc0abb3619ebc1a5f

**Comment by deliciouslytyped** [comment] 2023-04-14 02:05
Thanks both of you for taking such a good look at this!
(Indeed, I didn't think of just using the standard formats with the TO_ functions.)

Date types seem to be one of the most complicated, and I dread to use them.
https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca "Falsehoods programmers believe about time"
