### ISSUE TITLE
DATE(timestamp, timezone) produces timestamp instead of date when transpiled from BigQuery to DuckDB

### ISSUE THREAD

**Issue by Giganoide01** [tobymao/sqlglot#3562] opened 2024-05-28 21:53 UTC
Recently I was writing a query in SQLMesh and noticed that the BigQuery command `DATE(TIMESTAMP_MICROS(timestamp), 'America/Recife')` was returning a TIMESTAMP WITH TIME ZONE object when converted to DuckDB through sqlglot, instead of returning a DATE object as in BigQuery.

**Environment Versions**
1. Ubuntu 22.04.3 LTS
2. Python 3.11.7
3. sqlglot 24.0.0
4. duckdb v0.10.3 70fd6a8a24

**Steps to replicate**
1. In BigQuery, run the command `SELECT DATE(TIMESTAMP_MICROS(946695600000000), 'America/Recife')` , it should return `2000-01-01`, a DATE type.

2. Run the following command in Python to convert it to DuckDB using sqlglot:
```
import sqlglot
sqlglot.transpile("SELECT DATE(TIMESTAMP_MICROS(946695600000000), 'America/Recife')", read="bigquery", write="duckdb")[0]
```

  * The output command should be: `SELECT STRPTIME(STRFTIME(CAST(MAKE_TIMESTAMP(946695600000000) AS DATE), '%d/%m/%Y') || ' ' || 'America/Recife', '%d/%m/%Y %Z')`

3. Get the outputted command and run it in DuckDB. It should return `2000-01-01 00:00:00-02`, a TIMESTAMP WITH TIME ZONE object.

I expected the conversion to keep the data type from the original command, that the converted command from sqlglot looked something like `SELECT CAST(STRPTIME(STRFTIME(CAST(MAKE_TIMESTAMP(946695600000000) AS DATE), '%d/%m/%Y') || ' ' || 'America/Recife', '%d/%m/%Y %Z') AS DATE)`.

Therefore, I want to know if this is an expected behavior from sqlglot.

**Comment by georgesittas** [comment] 2024-05-28 23:14
This looks like expected behavior to me. I don't think DuckDB supports `DATE` with time zone info, so in order to preserve that information it converts it into a `TIMESTAMP WITH TIME ZONE` and formats it accordingly.

Closing the ticket as not planned, since I don't see an action item, but happy to continue discussing in this thread and possibly reopen it if there's a clear reason to change this. Also curious if this caused other issues in the context it showed up.

**Closed by georgesittas** 2024-05-28 23:14 UTC

**Comment by georgesittas** [comment] 2024-05-28 23:16
Hm, I somehow missed this section when I read the description earlier:

> I expected the conversion to keep the data type from the original command, that the converted command from sqlglot looked something like `SELECT CAST(STRPTIME(STRFTIME(CAST(MAKE_TIMESTAMP(946695600000000) AS DATE), '%d/%m/%Y') || ' ' || 'America/Recife', '%d/%m/%Y %Z') AS DATE)`.

What effect does the `CAST(... AS DATE)` have when there is a time zone in the timestamp? Are the two forms equivalent? I'd need to understand a bit more if that's a reasonable conversion to implement or not.

**Comment by georgesittas** [comment] 2024-05-28 23:42
Adding that `CAST` doesn't seem correct. For example, in BigQuery you get the following which is correct:

<img width="740" alt="Screenshot 2024-05-29 at 2 40 58 AM" src="https://github.com/tobymao/sqlglot/assets/46752250/e1049793-0bcb-4119-a789-a64d1a441930">

But in DuckDB you get this:

```
>>> duckdb.query("SELECT CAST(STRPTIME(STRFTIME(CAST(CURRENT_TIMESTAMP AS DATE), '%d/%m/%Y') || ' ' || 'America/Recife', '%d/%m/%Y %Z') AS DATE)")
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CAST(strptime(((strftime(CAST(CURRENT_TIMESTAMP AS DATE), '%d/%m/%Y') || ' ') || 'America/Recife'), '%d/%m/%Y %Z') AS DATE) │
│                                                            date                                                             │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 2024-05-29                                                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

>>> duckdb.query("SELECT CAST(STRPTIME(STRFTIME(CAST(CURRENT_TIMESTAMP AS DATE), '%d/%m/%Y') || ' ' || 'Europe/Athens', '%d/%m/%Y %Z') AS DATE)")
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CAST(strptime(((strftime(CAST(CURRENT_TIMESTAMP AS DATE), '%d/%m/%Y') || ' ') || 'Europe/Athens'), '%d/%m/%Y %Z') AS DATE) │
│                                                            date                                                            │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 2024-05-29                                                                                                                 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Giganoide01** [comment] 2024-05-29 17:46
> What effect does the CAST(... AS DATE) have when there is a time zone in the timestamp? Are the two forms equivalent? I'd need to understand a bit more if that's a reasonable conversion to implement or not.

All it does is convert the TIMESTAMP WITH TIME ZONE data type to DATE data type, to keep only the `yyyy-mm-dd` part of the information.

It is also the transpiled command generated from `sqlglot.transpile("SELECT DATE(TIMESTAMP_MICROS(946695600000000), 'America/Recife')::DATE", read="bigquery", write="duckdb")[0]`. That's why I thought it would be more correct than the actual one.

Although, as you have shown in the second part, it also has some incorrect behaviors in DuckDB.
