### ISSUE TITLE
escaped `\0` characters in clickhouse are interpreted as null bytes

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2325] opened 2023-09-26 10:48 UTC
**Fully reproducible code snippet**

```
In [17]: import sqlglot as sg

In [18]: expr = sg.parse_one("select '\\0'").sql("clickhouse")

In [19]: expr
Out[19]: "SELECT '\\0'"

In [20]: print(expr)
SELECT '\0'

In [21]: !clickhouse local <<< "$expr"
\0

In [22]: !clickhouse local <<< "SELECT ASCII('\0')"
0

In [23]: !clickhouse local <<< "SELECT ASCII('\1')"
92

In [24]: !clickhouse local <<< "SELECT ASCII('\x01')"
1
```

I think because `\\0` in Python means "the character `\` followed by the character `0`" and not "the null byte", sqlglot should backslash-escape `\0` strings.

Note that it seems to be specific to `\0` and not other backslashed characters:

```
In [29]: !clickhouse local <<< "SELECT '\0'"
\0

In [30]: !clickhouse local <<< "SELECT '\1'"
\\1
```

**Official Documentation**

https://clickhouse.com/docs/en/sql-reference/syntax#string

**Comment by GeorgeSittas** [comment] 2023-09-26 13:14
Should it be `expr = sg.parse_one("select '\0'").sql("clickhouse")` instead of including a double escape?

**Comment by cpcloud** [comment] 2023-09-26 13:15
`\0` is a null byte, so I don't think so:

```
>>> '\0'
'\x00'
>>> ord('\0')
0
```

**Comment by GeorgeSittas** [comment] 2023-09-26 13:16
What's the intent here though? What are you trying to transpile (read, write, etc)?

**Comment by cpcloud** [comment] 2023-09-26 13:21
I'm trying to generate code for regular expression replacement with ClickHouse and I want the meaning of escaped strings to match that of Python:

Escaped:

```
albatross :) select REGEXP_REPLACE('ab', '.', '\\0\\0'); -- works because of the escape

SELECT REGEXP_REPLACE('ab', '.', '\\0\\0')

Query id: 8c549122-cca0-4dd4-a923-0b8ad85ab7a8

┌─replaceRegexpAll('ab', '.', '\\0\\0')─┐
│ aabb                                  │
└───────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

Unescaped:

```
albatross :) select REGEXP_REPLACE('ab', '.', '\0\0'); -- fails because \0 means null byte

SELECT REGEXP_REPLACE('ab', '.', '\0\0')

Query id: 0c55ab1f-dc8d-4290-a0dc-c331a37f8d0f

┌─replaceRegexpAll('ab', '.', '\0\0')─┐
│                                     │
└─────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```


I want `"\\0"` to have the same meaning in generated SQL that it does in Python: a backslash character followed by a zero character.

**Comment by cpcloud** [comment] 2023-09-26 13:23
To be totally clear: this is only a problem with the string `'\0'` in ClickHouse, other singly-escaped numbers are not interpreted as bytes:

```
albatross :) select '\0', '\1', '\2';

SELECT
    '\0',
    '\\1',
    '\\2'

Query id: f19d4297-ae74-4f17-abf3-34d159e97e0b

┌─'\0'─┬─'\\1'─┬─'\\2'─┐
│      │ \1    │ \2    │
└──────┴───────┴───────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by GeorgeSittas** [comment] 2023-09-26 13:33
I'm probably a bit confused with the escapes, but if the intended / correct ClickHouse query is

```sql
SELECT REGEXP_REPLACE('ab', '.', '\\0\\0');
```

Shouldn't you pass a query like the following in Python?

```sql
SELECT REGEXP_REPLACE('ab', '.', '\\\\0\\\\0');
```

**Comment by cpcloud** [comment] 2023-09-26 13:37
That is in fact what needs to happen :)

I am wondering whether this is something sqlglot should handle, otherwise a trivial `sg.select("\\0")` won't be portable.

Here's DuckDB:

```
D select '\0', ascii('\0');
┌─────────┬─────────────┐
│  '\0'   │ ascii('\0') │
│ varchar │    int32    │
├─────────┼─────────────┤
│ \0      │          92 │
└─────────┴─────────────┘
```

**Comment by GeorgeSittas** [comment] 2023-09-26 14:02
Ok, let's say you had the following file which contains ClickHouse SQL:

```
➜  Downloads cat > some_sql.txt
SELECT '\\0'

**Comment by cpcloud** [comment] 2023-09-26 14:05
That's not the same thing as the string `"SELECT '\\0'"` though because `__str__` and `__repr__` are different.

**Comment by GeorgeSittas** [comment] 2023-09-26 14:06
Ok, let's say you had the following file which contains ClickHouse SQL:

```
➜ cat some_sql.txt
SELECT '\\0'
```

If you read this file in python and then call `transpile` on its contents, you get this

```
>>> with open('some_sql.txt', 'r') as f:
...     import sqlglot
...     sqlglot.transpile(f.read(), "clickhouse")
...
["SELECT '\\\\0'"]
```

This means that the "output" SQL is essentially `SELECT '\\0'`, which is equivalent to the input you had in the file. I think this is the intended behavior and it's how SQLGlot is expected to work, cc @tobymao isn't that right?

**Comment by GeorgeSittas** [comment] 2023-09-26 14:08
It's very likely that my understanding is off somewhere here, escapes are confusing, especially when you add another layer which is Python and yet another which is transpiling them correctly across dialects. Feels like a mess :)

**Comment by cpcloud** [comment] 2023-09-26 14:08
Yes, your example is what I would expect, but it's not the same as the Python string `"SELECT '\\0'"`

**Comment by cpcloud** [comment] 2023-09-26 14:22
I guess it's not totally clear why an escape would be different than any other string. `"abcd"` means one thing in Python, so why would introducing escapes change that?

I understand there may be practical reasons for there to be a difference 🙂

**Comment by GeorgeSittas** [comment] 2023-09-26 18:03
> "abcd" means one thing in Python, so why would introducing escapes change that?

Another example that comes to mind is `SELECT '\'` which is valid Postgres SQL, since `\` is not an escape character. If you wanted to feed this query into SQLGlot, you'd have to escape the `\`, i.e.

```python
sqlglot.transpile("SELECT '\\'", "postgres")
```

The way my argument above applies here is that, since you pass in `SELECT '\'` to `psql` to execute it, you treat that text as a "raw string" and then escape it as needed to represent it in Python.

**Comment by cpcloud** [comment] 2023-09-26 18:23
I think it's clickhouse is an exception because the postgres semantics match python semantics:

- "one backslash" in python is `"\\"`
- "one backslash" in postgres is `'\'`

For clickhouse (and only in the null byte case) it's different:

- "one null byte" in python is `"\0"`
- "one null byte" in clickhouse is `'\0'`, which must only be written as `"\\0"` (the sequence of an escaped backslash and the character `"0"`) in python.

I'm interested in preserving the semantics of the notation.

A string that I write in python should have the same meaning in the database, ideally.

**Comment by GeorgeSittas** [comment] 2023-09-26 18:51
> A string that I write in python should have the same meaning in the database, ideally.

I'm not sure if this is a reasonable request. The correct way to represent a SQL query in python is to copy whatever you get back by reading a file that contains that query. Coming back to the initial example:

```
➜ cat some_sql.txt
SELECT '\\0'
➜ python
Python 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('some_sql.txt', 'r') as f:
...     f.read()
...
"SELECT '\\\\0'\n"
>>> import sqlglot
>>> sqlglot.transpile("SELECT '\\\\0'", "clickhouse")
["SELECT '\\\\0'"]
>>> print(sqlglot.transpile("SELECT '\\\\0'", "clickhouse")[0])
SELECT '\\0'
```

You can imagine that `some_sql.txt` contains the business logic of a model, for example, and so that's the source of truth because that's what will hit the underlying engine. Since python reads that in and represents it as `"SELECT '\\\\0'\n"`, then it's the user's responsibility to pass _exactly_ that string in the methods of interest, e.g. `transpile`.

If you instead wanted a string with a single "null byte character", you'd store that in the file as `SELECT '\0'` and that'd be read in as `"SELECT '\\0'"` in python, which would produce the same thing if you were to print it. This means a roundtrip of storing a ClickHouse query and generating it back using SQLGlot would produce the exact same thing.

I believe this is the intended behavior, so I'm going to ahead and close this issue for now. Feel free to reach out in slack though if you feel like I'm misinterpreting your point and we can continue chatting there (probably easier than async :D).

**Closed by GeorgeSittas** 2023-09-26 18:51 UTC
