### ISSUE TITLE
Cannot use convert function 

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#1214] opened 2023-02-22 13:05 UTC
Hi,

I have an sql query that converts a date to varchar in the where clause but when I try to parse the it through sqlglot, I get an error.

```
SELECT * FROM table_name WHERE CONVERT(VARCHAR(20), date_field, 101) LIKE '%1239%'
```

Error: keyword 'to' missing for exp.CAST

**Comment by GeorgeSittas** [comment] 2023-02-22 13:14
I suppose this is T-SQL, for which I can't reproduce the error:

```python
>>> import sqlglot
>>> sqlglot.transpile("SELECT * FROM table_name WHERE CONVERT(VARCHAR(20), date_field, 101) LIKE '%1239%'", read="tsql")
["SELECT * FROM table_name WHERE CAST(FORMAT(date_field, 'MM/dd/yyyy') AS VARCHAR(20)) LIKE '%1239%'"]
```

I'm closing this for now, happy to reopen if there's an actual issue I missed.

**Closed by GeorgeSittas** 2023-02-22 13:14 UTC
