### ISSUE TITLE
TIMESTAMP / TIME WITH TIME ZONE does not support any modifiers

### ISSUE THREAD

**Issue by jay-emis** [tobymao/sqlglot#3989] opened 2024-08-28 10:53 UTC
**Is your feature request related to a problem? Please describe.**
Error on loading trino models to duckduckdb on testing: uckdb.duckdb.ConversionException: Conversion Error: Unimplemented type for cast (TIMESTAMP WITH TIME ZONE -> TIME)
LINE 1: ...ime" AS DATE) AS "session_start_date", CAST("session"."startdatetime" AS TIME)...
if input in this format: enddatetime::TIME(6)

**Describe the solution you'd like**
Handle time without precision or handle casts and format result to desired precision.

**Describe alternatives you've considered**

**Additional context**

**Comment by georgesittas** [comment] 2024-08-28 10:58
Hi, it's not clear to me what the problem is here so I'm closing this for now. For what it's worth, I believe this works fine:

```python
>>> from sqlglot import parse_one
>>> parse_one("SELECT CAST('12:05:01'AS TIME(6))", "trino").sql("duckdb")
"SELECT CAST('12:05:01' AS TIME)"
```

Happy to reopen if you provide sufficient details and examples that demonstrate the problem clearly.

**Comment by georgesittas** [comment] 2024-08-28 15:00
I see, thanks for clarifying. This is the repro I came up with:

```python
>>> from sqlglot import transpile
>>> transpile("SELECT CAST(FROM_ISO8601_TIMESTAMP('2020-05-11T11:15:05') AS TIME(6)) AS col;", "trino", "duckdb")
["SELECT CAST(CAST('2020-05-11T11:15:05' AS TIMESTAMPTZ) AS TIME) AS col"]
```

The `FROM_ISO8601_TIMESTAMP` call doesn't really matter, I just wanted to use a timestamp with time zone to produce the failure due to the `TIMESTAMPTZ` --> `TIME` cast in DuckDB.

We'll take a look, cc @VaggelisD.

**Comment by jay-emis** [comment] 2024-08-28 15:11
Thats great. Thanks. I am happy to create a bugfix PR if needed.

**Comment by georgesittas** [comment] 2024-08-28 15:21
Btw - what's the intention behind casting a timestamp with time zone info into `TIME(6)` in this case? Aren't you getting rid of the zone info there? Or is that intentional? Not sure what's the best way to deal with this in DuckDB.

**Comment by jay-emis** [comment] 2024-08-28 15:49
We are trying to extract the date and time separately from a time object ('2019-07-22 12:04:18.370000+01:00') here for another table. Not sure if there is a better approach for this.

**Comment by georgesittas** [comment] 2024-08-28 18:28
Wouldn't casting to `TIME(6) WITH TIME ZONE` be more fitting here? Since your original timestamp has a time zone.

**Comment by jay-emis** [comment] 2024-08-29 14:01
> Wouldn't casting to `TIME(6) WITH TIME ZONE` be more fitting here? Since your original timestamp has a time zone.

I tried this one, got this error:
duckdb.duckdb.NotImplementedException: Not implemented Error: Unsupported type "TIME WITH TIME ZONE"

**Comment by jay-emis** [comment] 2024-08-29 14:21
I did i think. I changed in the model from 
```  
  session.startdatetime::DATE AS session_start_date,
  session.startdatetime::TIME(6) AS session_start_time,
  session.enddatetime::DATE AS session_end_date,
  session.enddatetime::TIME(6) AS session_end_time,


to 
```  session.startdatetime::DATE AS session_start_date,
  session.startdatetime::TIME(6) WITH TIME ZONE AS session_start_time,
  session.enddatetime::DATE AS session_end_date,
  session.enddatetime::TIME(6) WITH TIME ZONE AS session_end_time,

**Comment by georgesittas** [comment] 2024-08-29 14:32
Did this work for you? Both the model and the unit test ran as expected?

**Comment by georgesittas** [comment] 2024-08-30 15:23
It seems like this transpilation is more nuanced than we initially anticipated, so I'll go ahead and close this for now to avoid introducing iffy logic. For SQLMesh, you could consider running that specific unit [test against Trino](https://sqlmesh.readthedocs.io/en/stable/concepts/tests/?h=test#using-a-different-testing-connection) if necessary, or try changing the model like we discussed and see if that works.

**Closed by georgesittas** 2024-08-30 15:23 UTC

**Comment by jay-emis** [comment] 2024-08-30 15:25
Yes, we realized the same. We are looking at running the tests with a trino docker container or spark. Thanks for looking into it.

**Comment by georgesittas** [comment] 2024-08-30 15:26
Sounds good, thanks for following up 👍
