### ISSUE TITLE
Double lateral view explode without table alias issue with optimizer scoping

### ISSUE THREAD

**Issue by eakmanrq** [tobymao/sqlglot#1185] opened 2023-02-15 22:39 UTC
Example query:
```
SELECT
    cola,
    exploded_values1,
    exploded_values2
FROM
    db.table
    LATERAL VIEW EXPLODE(array_values1) AS exploded_values1
    LATERAL VIEW EXPLODE(array_values2) AS exploded_values2
```

The issue is that we don't assign table aliases to the two explodes and therefore they get an alias of empty string. When the source map is created in the scope class the empty string conflict and it no longer has an understanding that there are two unique sources here. This can impact functions like `annotate_types` and throw an error saying `exploded_values2` doesn't exist since it is not seen as a column it is not registered as a source.

**Comment by tobymao** [comment] 2023-02-15 23:46
cannot reproduce, was probably fixed by @barakalon in his refactor

```
SELECT
  "table"."cola" AS "cola",
  "_q_0"."exploded_values1" AS "exploded_values1",
  "_q_1"."exploded_values2" AS "exploded_values2"
FROM "db"."table" AS "table"
LATERAL VIEW
EXPLODE("table"."array_values1") _q_0 AS "exploded_values1"
LATERAL VIEW
EXPLODE("table"."array_values2") _q_1 AS "exploded_values2"```

**Closed by tobymao** 2023-02-15 23:46 UTC
