### ISSUE TITLE
Redshift Dialect - GROUP BY clause causes parsing error although query is valid

### ISSUE THREAD

**Issue by mrmammadov** [tobymao/sqlglot#2411] opened 2023-10-15 12:56 UTC
**Fully reproducible code snippet**
``` CREATE OR REPLACE VIEW my_view AS
SELECT id,
       AVG(average_metric1)                   AS m1,
       AVG(average_metric2)                   AS m2
FROM table
GROUP BY id
WITH NO SCHEMA BINDING;
```
This query causes the following parsing error when running the below code, although query is valid in **Redshift**:

`parse(query, read="redshift")`

![image](https://github.com/tobymao/sqlglot/assets/19167079/f0552550-3ddf-4ecd-8cca-7306c4a8d069)

Removing `GROUP BY id` solves the parsing issue, however is not a valid Redshift query in that case.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by GeorgeSittas** [comment] 2023-10-15 13:21
Please make sure to either include documentation or examples that prove the syntax is valid, i.e. by actually running it against the engine and showing there's no syntax error.

In this case I tried running this query against Redshift and I got back a syntax error:

```
ERROR: syntax error at or near "WITH" Position: 28
```

Query:
```sql
SELECT *
FROM t
GROUP BY a
WITH NO SCHEMA BINDING;
```

I'm gonna go ahead and close this as a non-issue. Happy to continue chatting / reopen this if I missed something.

**Comment by mrmammadov** [comment] 2023-10-15 14:11
The only way of proving that syntax is right is by running it, I don't know how else.
The query above is adjusted for example purposes as the original one is company-internal and therefore confidential.

Regarding the documentation, there is no documentation that's pinpointing the error here. It's just an SQL knowledge that if there are aggregates in the SELECT statement, **the column(s) that aggregates are based on** should also be in `GROUP BY` statement. Here is docs if it helps: https://docs.aws.amazon.com/redshift/latest/dg/r_GROUP_BY_clause.html

I believe that `sqlglot` doesn't (or missed to) check the semantics of this query for Redshift. Please let me know where to start and I'm willing to work on it.

Lastly, I appreciate for this package and contributions, but closing down the issues right away seems like an odd choice here for me. At least, keep it open for a day or two for the discussions happening. 
Thanks!

**Comment by GeorgeSittas** [comment] 2023-10-15 15:04
Closing the issue doesn't mean we're not open to discussing it, it just means that given the provided information and our failure at attempting to reproduce it we deemed that there's no actual issue which matches the description. I mentioned this above too:

> Happy to continue chatting / reopen this if I missed something.

Also, I didn't close this one on a whim; I first tried to verify that your query verbatim or a variant of it works in Redshift, i.e. doesn't throw a syntax error, and after I failed to get it to work I visited [Redshift's documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_SELECT_synopsis.html#r_SELECT_synopsis-synopsis) on the `SELECT` expression, which also doesn't mention the `WITH NO SCHEMA BINDING` clause anywhere.

On another note, I investigated a bit more and I think the issue is actually related to the `CREATE VIEW` statement, which [does support](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_VIEW.html) this clause. Your original example indeed fails to be parsed by SQLGlot when used in that context, even though it's accepted by Redshift:

```python
>>> import sqlglot
>>> sqlglot.parse_one("""
... CREATE OR REPLACE VIEW v1 AS
... SELECT id,
...        AVG(average_metric1)                   AS m1,
...        AVG(average_metric2)                   AS m2
... FROM table
... GROUP BY id
... WITH NO SCHEMA BINDING;
... """, "redshift")
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 8, Col: 7.
               AS m1,
       AVG(average_metric2)                   AS m2
FROM table
GROUP BY id
WITH NO SCHEMA BINDING;
     ~~
```

**Closed** 2023-10-15 15:17 UTC

**Comment by mrmammadov** [comment] 2023-10-15 21:14
Got it! Once again, I much appreciate the efforts, keeping project going, didn't mean to criticise. 
> Closing the issue doesn't mean we're not open to discussing it, it just means that given the provided information and our failure at attempting to reproduce it we deemed that there's no actual issue which matches the description. I mentioned this above too:

Regarding `sqlglot` not parsing the `WITH NO SCHEMA BINDING` on `CREATE VIEW` statements, do you think that it's plausible to implement that? As it's accepted by Redshift.
I'm very much down to implement this feature and learn more about this package's internals. 
Thanks!

**Comment by GeorgeSittas** [comment] 2023-10-15 21:25
Thanks for the kind words!

> Regarding sqlglot not parsing the WITH NO SCHEMA BINDING on CREATE VIEW statements, do you think that it's plausible to implement that? As it's accepted by Redshift.

Yes, I addressed it earlier in https://github.com/tobymao/sqlglot/pull/2412, appreciate the offer though.

**Comment by mrmammadov** [comment] 2023-10-15 22:22
Awesome, thanks!
