### ISSUE TITLE
Columns Used in Equalities Mis-Parsed When Tables Are Unaliased

### ISSUE THREAD

**Issue by steven-luabase** [tobymao/sqlglot#1173] opened 2023-02-14 22:54 UTC
If I try to parse the equalities in the following query that does not use aliased tables:
```
from sqlglot import parse_one, exp
sql = '''
select 
    *
from quickbooks.customer
left join quickbooks.invoice 
    on quickbooks.invoice.customer_id = quickbooks.customer.id
'''
parsed_query = parse_one(sql, read='snowflake')
eqs = parsed_query.find(exp.EQ)
eqs
```
I get the following result:
```
(EQ this: 
  (DOT this: 
    (COLUMN this: 
      (IDENTIFIER this: invoice, quoted: False), table: 
      (IDENTIFIER this: quickbooks, quoted: False)), expression: 
    (IDENTIFIER this: customer_id, quoted: False)), expression: 
  (DOT this: 
    (COLUMN this: 
      (IDENTIFIER this: customer, quoted: False), table: 
      (IDENTIFIER this: quickbooks, quoted: False)), expression: 
    (IDENTIFIER this: id, quoted: False)))
```

I would expect the columns used in the equality to be `customer_id` and `id` but seems like the table names are being parsed as the columns here.

I know using unaliased tables is not very common but we're working with an outside customer's query history in which they rarely alias their tables when querying.

**Comment by paulgrow-octane** [comment] 2023-02-14 23:12
Similar vein as #1172.

**Comment by tobymao** [comment] 2023-02-14 23:14
duplicate of #1172

**Closed by tobymao** 2023-02-14 23:14 UTC
