### ISSUE TITLE
Parse error: character varying

### ISSUE THREAD

**Issue by CBQu** [tobymao/sqlglot#1176] opened 2023-02-15 07:01 UTC
I am trying to parse a create function sql. The error message is like this.

```
ParseError: Expecting ). Line 1, Col: 81.
  CREATE OR REPLACE FUNCTION function_name (input_a character varying DEFAULT NULL::character varying)
```
The first "character" is underlined.

It seems **character varying** cannot be parse correctly, which should be equivalent to VARCHAR.

> The notations varchar(n) and char(n) are aliases for character varying(n) and character(n), respectively. If specified, the length must be greater than zero and cannot exceed 10485760. character without length specifier is equivalent to character(1). If character varying is used without length specifier, the type accepts strings of any size.

Reference: https://www.postgresql.org/docs/current/datatype-character.html

**Comment by tobymao** [comment] 2023-02-15 07:09
can you post the sql / code so we can reproduce this?

**Comment by GeorgeSittas** [comment] 2023-02-15 07:11
I got a fix for this ready

**Comment by tobymao** [comment] 2023-02-15 07:16
did you just add the default parser to udf_kwarg?

**Comment by GeorgeSittas** [comment] 2023-02-15 07:17
https://github.com/tobymao/sqlglot/pull/1177

**Comment by tobymao** [comment] 2023-02-15 07:19
@CBQu you need to make sure to specify the dialect, in this case probably postgres

**Comment by GeorgeSittas** [comment] 2023-02-15 07:21
Right, `CHARACTER VARYING` was already supported. The error is because we weren't parsing additional information for each formal parameter, like DEFAULT _value_.

**Comment by CBQu** [comment] 2023-02-15 07:31
Thanks for the fast response. I tried ```parse_one(sql, read='postgres')``` and got this.

```
ParseError: Expecting ). Line 2, Col: 68.
  
CREATE OR REPLACE FUNCTION function_name(input_a character varying DEFAULT NULL::character varying)
 RETURNS void
 LANGUAGE plpgsql
 NOT FENCED NOT SHIPPABLE
AS $function$
```

Like @GeorgeSittas said. The error is now under DEFAULT.

**Comment by CBQu** [comment] 2023-02-15 07:35
After removing "DEFAULT NULL::character varying", the error becomes under "void" in the 2nd line.

My guess is that the semantics are not supported yet.

CREATE FUNCTION Reference: https://www.postgresql.org/docs/current/sql-createfunction.html

**Closed** 2023-02-15 17:13 UTC
