### ISSUE TITLE
Error occurs when parsing a decode function with > 3 arguments in PostgreSQL

### ISSUE THREAD

**Issue by cauwt** [tobymao/sqlglot#1491] opened 2023-04-27 05:10 UTC
# code:
```python
from sqlglot import parse_one
sql ="""
select d.a_id + e.b_id as id
, e.name 
, decode(a.id, '01', 'a', 'b')
from dwmdata.a as d
left join dwmdata.b as e 
on d.a_id = e.b_id 
limit 1000;
"""
tree = parse_one(sql,read='postgres')
```

# The following error is thrown:
sqlglot.errors.ParseError: The number of provided arguments (4) is greater than the maximum number of supported arguments (3). Line 4, Col: 30.

# What confuses me

in PostgreSQL, the function decode can legally have more than 3 arguments, but SQLglot throws error when parsing it.

**Comment by tobymao** [comment] 2023-04-27 05:15
i don't think postgres has a decode function, can you show me the documentation?

**Comment by tobymao** [comment] 2023-04-27 05:18
according to the documentation, decode only takes 2 arguments in postgres, i've also tried this on my local postgres. maybe you're getting confused with oracle's decode? 

closing for now

**Closed by tobymao** 2023-04-27 05:18 UTC

**Comment by cauwt** [comment] 2023-04-27 12:10
Sorry for late response. Seemingly the function is a UDF. So what can i do to avoid this error? Change the name to something like func_decode before parsing?

**Comment by GeorgeSittas** [comment] 2023-04-27 12:16
Hey, I can't reproduce this issue locally. Are you using the latest SQLGlot version?

```python
>>> import sqlglot
>>> sqlglot.__version__
'11.5.9'
>>> from sqlglot import parse_one
>>> sql ="""
... select d.a_id + e.b_id as id
... , e.name
... , decode(a.id, '01', 'a', 'b')
... from dwmdata.a as d
... left join dwmdata.b as e
... on d.a_id = e.b_id
... limit 1000;
... """
>>> parse_one(sql, read="postgres").sql(dialect="postgres")
"SELECT d.a_id + e.b_id AS id, e.name, CASE WHEN a.id = '01' THEN 'a' ELSE 'b' END FROM dwmdata.a AS d LEFT JOIN dwmdata.b AS e ON d.a_id = e.b_id LIMIT 1000"
```

**Comment by cauwt** [comment] 2023-04-27 13:02
The version of my local bineries is 11.1.2. maybe that's the reason. thanks.
