### ISSUE TITLE
Support spaces in identifiers when defined with backticks in sqlite

### ISSUE THREAD

**Issue by adamf** [tobymao/sqlglot#314] opened 2022-08-09 23:12 UTC
sqlite supports spaces in identifiers that have backticks:

```
sqlite> CREATE TABLE "z" (`a b` TEXT NOT NULL);
sqlite> .schema
CREATE TABLE IF NOT EXISTS "z" (`a b` TEXT NOT NULL);
```

sqlglot doesn't like this:
```
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 22.
  CREATE TABLE "z" (`a b` TEXT NOT NULL)
```
(col 22 is the `b`)

**Comment by tobymao** [comment] 2022-08-09 23:29
this is a dup of #302

the issue is that sqlite in sqlglot only support "" as identifier, you can use spaces within the identifier. so as a part of 302. Can you just change from backticks to double quotes?

closing for now as we can fix this with 302

**Closed by tobymao** 2022-08-09 23:29 UTC

**Comment by adamf** [comment] 2022-08-09 23:35
I can’t control the input SQLite files to my process, but I can for now do
a replace of all backticks with double quotes until 302 is fixed.
