### ISSUE TITLE
[Snowflake] `sqlglot.optimizer.qualify_tables.qualify_tables` qualifies `CONNECT BY` data sources when it shouldn't

### ISSUE THREAD

**Issue by florian-ernst-alan** [tobymao/sqlglot#4511] opened 2024-12-12 11:47 UTC
## `CONNECT BY` with `level_expression` feature spec
In Snowflake, the `SELECT FROM <data_source> START WITH ... CONNECT BY` construct doesn't officially allows aliasing the data source:
```sql
SELECT <column_list> [ , <level_expression> ]
  FROM <data_source>
    START WITH <predicate>
    CONNECT BY [ PRIOR ] <col1_identifier> = [ PRIOR ] <col2_identifier>
           [ , [ PRIOR ] <col3_identifier> = [ PRIOR ] <col4_identifier> ]
           ...
  ...
```

(see [documentation](https://docs.snowflake.com/en/sql-reference/constructs/connect-by#examples)).

For some reasons, it does work in some cases in practice, but it breaks another Snowflake `CONNECT BY...` feature: `level_expression`, which allows to get the current level of recursion depth.

For example, this works and is officially supported:
```sql
SELECT employee_ID,
        manager_ID, 
        title, 
        level # <-- `level` is **not** an employees column, it's a special construct
  FROM employees
    START WITH title = 'President'
    CONNECT BY manager_ID = PRIOR employee_id
  ORDER BY employee_ID;
```

The `level` column can be qualified, so this works and is officially supported:
```sql
SELECT employees.employee_ID,
        employees.manager_ID, 
        employees.title,
        employees.level # <-- this works 👍
  FROM employees
...
```

But if you alias the table **(which isn't officially supported)**, it breaks!
```sql
SELECT employee_ID,
        manager_ID, 
        title,
        level # <-- ❌ invalid identifier 'LEVEL'
  FROM employees AS e
    START WITH title = 'President'
    CONNECT BY manager_ID = PRIOR employee_id
  ORDER BY employee_ID;
...
```

## `qualify_tables` behavior

`qualify_tables` will always qualify the data_source in a `CONNECT BY` expression, breaking the `<level_expression>` feature.

From this:
```sql
SELECT employees.employee_ID,
        employees.manager_ID, 
        employees.title,
        employees.level # <-- this works 👍
  FROM employees
...
```

To this:
```sql
SELECT employees.employee_ID,
        employees.manager_ID, 
        employees.title,
        employees.level # <-- this breaks ❌
  FROM employees AS employees
...
```

## Fully reproducible code snippet

```py
from sqlglot import parse_one
from sqlglot.optimizer.qualify_tables import qualify_tables

SQL_DIALECT = "snowflake"

print(qualify_tables(parse_one("""
SELECT employee_ID, manager_ID, title, level
  FROM employees
    START WITH title = 'President'
    CONNECT BY
      manager_ID = PRIOR employee_id
  ORDER BY employee_ID;
""", dialect=SQL_DIALECT), schema=None, dialect=SQL_DIALECT).sql(pretty=True))
```

**Official Documentation**
[Connect By Documentation](https://docs.snowflake.com/en/sql-reference/constructs/connect-by#examples) - it also explains the `<level_expression>` feature.

**Comment by florian-ernst-alan** [comment] 2024-12-12 11:47
I'm happy to make a PR with some guidance 🙂

**Comment by georgesittas** [comment] 2024-12-12 12:51
I'm not quite sure I understand what the issue is here. The end-to-end example you provided for `qualify_tables` produces a query that behaves equivalently in Snowflake as far as I can tell. Can you please elaborate? The `qualify` rule also preserves semantics from what I saw.

**Comment by florian-ernst-alan** [comment] 2024-12-12 14:44
@georgesittas The end-to-end example provides a query that Snowflake cannot run. Let me rewrite the example using SQLGlot's formatting, so we can compare the diff easily.

Code:
```py
print(qualify_tables(parse_one("""
SELECT
  employee_ID,
  manager_ID,
  title,
  level
FROM employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST
""", dialect=SQL_DIALECT), schema=None, dialect=SQL_DIALECT).sql(pretty=True))
```

Input:
```sql
SELECT
  employee_ID,
  manager_ID,
  title,
  level
FROM employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST
```

Output:
```sql
SELECT
  employee_ID,
  manager_ID,
  title,
  level
FROM employees AS employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST
```

Diff:
```diff
SELECT
  employee_ID,
  manager_ID,
  title,
  level
- FROM employees
+ FROM employees AS employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST
```


-----

## Example

This alone is enough to fail. Since this query has been taken from Snowflake's documentation ([first example](https://docs.snowflake.com/en/sql-reference/constructs/connect-by#examples)), here's a walkthrough their entire example:

```sql
-- ✅
CREATE OR REPLACE TABLE employees (title VARCHAR, employee_ID INTEGER, manager_ID INTEGER);

-- ✅
INSERT INTO employees (title, employee_ID, manager_ID) VALUES
    ('President', 1, NULL),  -- The President has no manager.
        ('Vice President Engineering', 10, 1),
            ('Programmer', 100, 10),
            ('QA Engineer', 101, 10),
        ('Vice President HR', 20, 1),
            ('Health Insurance Analyst', 200, 20);

-- ✅ Input query
SELECT
  employee_ID,
  manager_ID,
  title,
  level
FROM employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST

-- Result:
+-----------+----------+--------------------------+-----+
|EMPLOYEE_ID|MANAGER_ID|TITLE                     |LEVEL|
+-----------+----------+--------------------------+-----+
|1          |null      |President                 |1    |
|10         |1         |Vice President Engineering|2    |
|20         |1         |Vice President HR         |2    |
|100        |10        |Programmer                |3    |
|101        |10        |QA Engineer               |3    |
|200        |20        |Health Insurance Analyst  |3    |
+-----------+----------+--------------------------+-----+

-- ❌  Output query
SELECT
  employee_ID,
  manager_ID,
  title,
  level
FROM employees AS employees
START WITH title = 'President'
CONNECT BY manager_ID = PRIOR employee_id
ORDER BY
  employee_ID NULLS LAST

-- Result:
-- [42000][904] SQL compilation error: error line 5 at position 2 invalid identifier 'LEVEL'
```

**Comment by georgesittas** [comment] 2024-12-12 15:14
I can't reproduce this, Snowflake executes this fine for me:

<img width="1156" alt="Screenshot 2024-12-12 at 5 13 30 PM" src="https://github.com/user-attachments/assets/730bf30a-e540-4baf-b670-a394606ce76c" />

Closing the ticket for now, I've tested various queries with `CONNECT BY` produced by SQLGlot's qualifier and they seemed fine. Let me know if you have another example I can test and if there's a bug I'll take a closer look.

**Closed by georgesittas** 2024-12-12 15:14 UTC

**Comment by georgesittas** [comment] 2024-12-12 18:18
Yeah, please open another ticket for this and we can take a look.
