### ISSUE TITLE
Trino's `DATE_TRUNC` is parsed as `TIMESTAMP_TRUNC` with the `unit` parsed as a `exp.Var`

### ISSUE THREAD

**Issue by maen-allaga** [tobymao/sqlglot#3747] opened 2024-07-08 19:30 UTC
When parsing a Trino's sql, DateTrunc is only parsed as DateTrunc if the input is explicitly casted as `DATE`, otherwise it's parsed as `TIMESTAMPTRUNC`.
However, Trino (and Presto) don't have a `timestamp_trunc` function, their `date_trunc` function can handle both date and timestamp types.

**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`: Done
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`: Done
- Check if the issue still exists on main: Done

**Fully reproducible code snippet**
```python
from sqlglot import parse

if __name__ == '__main__':
    sqlstr = """SELECT
                DATE_TRUNC('year', CAST(startDate AS DATE)) AS year_start,
                DATE_TRUNC('minute', CAST(startDate AS DATETIME)) AS minute_start
            FROM tmp"""
    expression_tree = parse(sqlstr, read="trino", dialect="trino")
    print(repr(expression_tree))
```

Output:
```
[Select(
  expressions=[
    Alias(
      this=DateTrunc(   # <------- Correct parsing of DateTrunc function
        unit=Literal(this=YEAR, is_string=True),   # <------- Unit parsed as Literal
        this=Cast(
          this=Column(
            this=Identifier(this=startDate, quoted=False)),
          to=DataType(this=Type.DATE, nested=False))),
      alias=Identifier(this=year_start, quoted=False)),
    Alias(
      this=TimestampTrunc(   # <------- Incorrect parsing of DateTrunc function as TimestampTrunc
        this=Cast(
          this=Column(
            this=Identifier(this=startDate, quoted=False)),
          to=DataType(this=Type.DATETIME, nested=False)),
        unit=Var(this=MINUTE)),   # <------- Unit parsed as Var
      alias=Identifier(this=minute_start, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=tmp, quoted=False))))]
```

**Official Documentation**
* Trino's date_trunc function: https://trino.io/docs/current/functions/datetime.html#date_trunc
* Presto's date_trunc function: https://prestodb.io/docs/current/functions/datetime.html#date_trunc

**Comment by georgesittas** [comment] 2024-07-08 20:55
This is expected behavior @maen-allaga. The AST is produced like this to facilitate transpilation. The difference in the unit nodes does look weird though, @tobymao do you remember why you created a string literal [here](https://github.com/tobymao/sqlglot/commit/a4e899aaba317028480a440faeddb026bb464890#diff-7857fedd1d1451b1b9a5b8efaa1cc292c02e7ee4f0d04d7e2f9d5bfb9565802cR4559-R4569)?

**Comment by georgesittas** [comment] 2024-07-08 21:12
Should we switch to `Var` for it? Seems more consistent with `TimeUnit`.

**Comment by georgesittas** [comment] 2024-07-08 21:18
> are you saying the AST is dialect-agnostic?

That's exactly right. SQLGlot tries to preserve as much info as possible in the AST so that it can (a) generate the correct SQL when roundtripping (parse & generate using the same dialect), and (b) transpile towards other dialects.

> Are there any edge cases that we need to handle when our dialect is Trino, and we get an AST that has TIMESTAMP_TRUNC?

Not sure what edge cases you mean here, but if I understand correctly you are currently looking for `DateTrunc` expressions, e.g. using `isinstance` checks or methods such as `find_all`? If so, then you could update those calls to simply also look for `TimestampTrunc`, thus handling this AST pecularity.

> On the unit issue, isn't Var a Variable?

The `Var` expression is used to represent non-identifier "variables", such as keywords, date parts (this example), etc. Can you elaborate on what's the error you encountered?

**Comment by maen-allaga** [comment] 2024-07-08 21:24
> > are you saying the AST is dialect-agnostic?
> 
> That's exactly right. SQLGlot tries to preserve as much info as possible in the AST so that it can (a) generate the correct SQL when roundtripping (parse & generate using the same dialect), and (b) transpile towards other dialects.
> 
> > Are there any edge cases that we need to handle when our dialect is Trino, and we get an AST that has TIMESTAMP_TRUNC?
> 
> Not sure what edge cases you mean here, but if I understand correctly you are currently looking for `DateTrunc` expressions, e.g. using `isinstance` checks or methods such as `find_all`? If so, then you could update those calls to simply also look for `TimestampTrunc`, thus handling this AST pecularity.

Great, that's what I wanted to confirm (I can handle TimestampTrunc and DateTrunc the same).
 
> > On the unit issue, isn't Var a Variable?
> 
> The `Var` expression is used to represent non-identifier "variables", such as keywords, date parts (this example), etc. Can you elaborate on what's the error you encountered?

It sounds like I didn't have the right assumption around `Var` node. When you say it's non-identifier variables. How do you suggest we should interpret the `Var` node when parsing the tree? should we just handle it similar to literal strings?

**Comment by georgesittas** [comment] 2024-07-08 21:32
> How do you suggest we should interpret the Var node when parsing the tree? should we just handle it similar to literal strings?

It depends on your use case, really. The `Var` simply wraps around some text, that's all. You can access that text by using `expr.name`.

**Comment by maen-allaga** [comment] 2024-07-08 21:43
> > How do you suggest we should interpret the Var node when parsing the tree? should we just handle it similar to literal strings?
> 
> It depends on your use case, really. The `Var` simply wraps around some text, that's all. You can access that text by using `expr.name`.

That's fair, I confirmed that's sqlglot transform it back to a literal here (https://github.com/tobymao/sqlglot/blob/15ca924ac6e8a72396a882c394856e466cae9ac3/sqlglot/dialects/dialect.py#L1240), which is what I will be doing.

**Comment by georgesittas** [comment] 2024-07-08 21:44
Sounds good. I'll close this issue as completed then and look into the `DateTrunc` thing separately since it's its own thing.

**Closed by georgesittas** 2024-07-08 21:44 UTC

**Comment by tobymao** [comment] 2024-07-08 21:49
sure we can covert it to a var
